parameters:
  neoconnect.transaction.commit_strategy.stack_commit_strategy.class: Neoxygen\NeoConnect\Transaction\Strategy\StackCommitStrategy

services:
  neoconnect.transaction.stack_commit_strategy:
    class: "%neoconnect.transaction.commit_strategy.stack_commit_strategy.class%"
    arguments: ["@neoconnect.event_dispatcher"]
