<?php

namespace Neoxygen\NeoConnect\Console;

use Symfony\Component\Console\Question\ChoiceQuestion,
    Symfony\Component\Filesystem\Filesystem,
    Symfony\Component\Console\Command\Command,
    Symfony\Component\Console\Input\InputInterface,
    Symfony\Component\Console\Input\InputOption,
    Symfony\Component\Console\Output\OutputInterface,
    Symfony\Component\Yaml\Yaml;

class ConfigBootstrapCommand extends BaseCommand
{
    const CFNAME = 'neoconnect.yml';

    protected function configure()
    {
        $this->setName('config:bootstrap')
            ->setDescription('Creates a PHP setup boostrap file based on your neoconnect.yml file settings')
            ->addOption(
                'overwrite',
                false,
                InputOption::VALUE_OPTIONAL,
                'Whether or not to overwrite exisiting bootstrap file'
            );
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output);

        $fs = new Filesystem();
        $cwd = getcwd();
        $file = $cwd.'/'.self::CFNAME;

        if (!$fs->exists($file)) {
            $output->writeln('<error>The config file "'.self::CFNAME.'" could not be found.</error>');
            $output->writeln(('<comment>You can generate this file with the "config:create" command</comment>'));
        } else {
            $config = Yaml::parse($file);
            $script = $this->createBootstrapFile($config, $file);
            $fs->mkdir($cwd.'/config', 0777, true);
            $fs->touch($cwd.'/config/neoconnect_bootstrap.php');
            $fs->dumpFile($cwd.'/config/neoconnect_bootstrap.php', $script);
            $output->writeln('<info>Bootstrap file "neoconnect_bootstrap.php" created in '.$cwd.'</info>');

        }
    }

    private function createBootstrapFile(array $config = array(), $file)
    {
        $fscript = "";
        $fscript .= "
<?php
/*
 * This file has been generated by the NeoConnect ".self::VERSION." package.
 *
 * Instead of modifying configuration settings here, you should better do it in your neoconnect.yml file present
 * at the root of your project and regenerate the bootstrap with the 'config:bootstrap' command.
 *
 */
\$con = \\Neoxygen\\NeoConnect\\ConnectionBuilder::create()
    ->loadConfigurationFromFile('$file')
    ->build();";

        return $fscript;
    }
}
