parameters:
  neoconnect.connection_manager.class: "Neoxygen\\NeoConnect\\Connection\\ConnectionManager"
  neoconnect.connection.class: "Neoxygen\\NeoConnect\\Connection\\Connection"
  neoconnect.commit_manager.class: "Neoxygen\\NeoConnect\\Commit\\CommitManager"
  neoconnect.query_manager.class: "Neoxygen\\NeoConnect\\Query\\QueryManager"
  neoconnect.event_dispatcher.class: "Neoxygen\\NeoConnect\\EventDispatcher\\EventDispatcher"
  neoconnect.flusher.class: "Neoxygen\\NeoConnect\\Flusher\\Flusher"

services:

  neoconnect.connection_manager:
    class: "%neoconnect.connection_manager.class%"
    arguments: ["%neoconnect.connection.class%"]

  neoconnect.commit_manager:
    class: "%neoconnect.commit_manager.class%"
    arguments: ["@neoconnect.connection_manager", "@neoconnect.ca_event_dispatcher"]

  neoconnect.query_manager:
    class: "%neoconnect.query_manager.class%"
    arguments: ["@neoconnect.connection_manager", "@neoconnect.commit_manager"]

  neoconnect.event_dispatcher:
    class: "%neoconnect.event_dispatcher.class%"

  neoconnect.ca_event_dispatcher:
    class: "Neoxygen\\NeoConnect\\EventDispatcher\\CAEVentDispatcher"
    arguments: ["@service_container"]

  neoconnect.flusher:
    class: "%neoconnect.flusher.class%"
    tags:
      - { name: flush.event_subscriber, class: "Flusher", service: "neoconnect.flusher" }
