parameters:
  neoconnect.connection_manager.class: "Neoxygen\\NeoConnect\\Connection\\ConnectionManager"
  neoconnect.connection.class: "Neoxygen\NeoConnect\Connection\Connection"

services:

  neoconnect.connection_manager:
    class: "%neoconnect.connection_manager.class%"
    arguments: ["%neoconnect.connection.class%"]
