parameters:
  neoconnect.transaction.commit_strategy: auto
  neoconnect.transaction.stack_flush_limit: 10

services:
  neoconnect.http_client:
    class: "%neoconnect.connection.class%"
    arguments: ["%neoconnect.connection.scheme%","%neoconnect.connection.host%","%neoconnect.connection.port%","@neoconnect.event_dispatcher"]

  neoconnect.event_dispatcher:
    class: "Neoxygen\\NeoConnect\\EventDispatcher\\EventDispatcher"

  neoconnect.deserializer:
    class: "Neoxygen\\NeoConnect\\Deserializer\\Deserializer"

  neoconnect.api_discovery:
    class: "Neoxygen\\NeoConnect\\Api\\Discovery"
    arguments: ["@neoconnect.http_client", "@neoconnect.deserializer"]

  neoconnect.transaction_manager:
    class: "Neoxygen\\NeoConnect\\Transaction\\TransactionManager"
    arguments:
      - "%neoconnect.transaction.commit_strategy%"
      - "%neoconnect.transaction.stack_flush_limit%"
      - "@neoconnect.http_client"
      - "@neoconnect.api_discovery"
      - "@neoconnect.deserializer"
      - "@neoconnect.event_dispatcher"
